os: osx
osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - go
      - zsh
      - cmake
      - ninja
      - automake
      - autoconf
      - libtool
    update: true
before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | zsh
install: skip
branches:
  only:
    - master
    - main
script:
  - ./build.sh
