os: osx
osx_image: xcode12.4
addons:
  homebrew:
    packages:
      - rustup
      - go
      - zsh
      - cmake
      - ninja
      - automake
      - autoconf
      - libtool
    update: true
before_install:
  - rustup-init -y
install: skip
branches:
  only:
    - master
    - main
script:
  - ./build.sh
