os: osx
osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - go
      - rust
      - zsh
      - cmake
      - ninja
      - automake
      - libtool
    update: true
install: skip
branches:
  only:
    - master
    - main
script:
  - ./build.sh
